version: "3"
services:
  api:
    container_name: api_atenas
    build: .
    restart: "always"
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - external-proxy_external-network

  db:
    container_name: db_atenas
    image: mysql:latest
    restart: "always"
    environment:
      MYSQL_DATABASE: atenas
      MYSQL_USER: atenas
      MYSQL_PASSWORD: atenas
      MYSQL_ROOT_PASSWORD: atenas
    volumes:
      - "/var/run/mysql:/var/run/mysql"
    ports:
      - "3306:3306"
    networks:
      - external-proxy_external-network

networks:
  external-proxy_external-network:
    external: true
