version: "3"
services:
  api:
    build: .
    container_name: api_atenas
    restart: "always"
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    container_name: db_atenas
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: atenas
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3307"

volumes:
  dbdata:
